config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'posts/closed_posts' => 'posts#closed_posts', as: 'closed_posts'
  get 'about/index'
  get 'help/index'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  root 'organizations#index'



  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'registrations/show/:id' => 'registrations#show', as: 'user_profile'
  end


  # scope '(/:locale)', locale: /ru/, defaults: { locale: I18n.locale } do
    ActiveAdmin.routes(self)
  # end


  resources :organizations,  only: [ :new, :create, :edit, :update, :destroy]

  post 'organizations/new'

  get 'organizations/show/:id' => 'organizations#show', as: 'organization_show'

  get 'organizations/edit/:id' => 'organizations#edit', as: 'organization_edit'

  get 'organizations/list' => 'organizations#list', as: 'organizations_list'

  get 'organizations/donors' => 'organizations#donors', as: 'donors'

  resources :posts

  resources :post_comments, only: [:create, :edit, :update, :destroy]
  resources :aids

  put 'posts/deactivate/:id' => 'posts#deactivate', as: 'post_deactivate'
  put 'posts/closed/:id' => 'posts#closed', as: 'post_closed'
  put 'organizations/deactivate/:id' => 'organizations#deactivate', as: 'organization_deactivate'
  post 'organizations/participation_request/:id' => 'organizations#participation_request', as: 'organization_participation_request'
  put 'organizations/approved/:id' => 'organizations#approved', as: 'organization_approved'
  put 'aids/accepted/:id' => 'aids#accepted', as: 'aid_accepted'
  get 'organizations/filter_organizations/:id' => 'organizations#filter_organizations', as: 'filter_organizations'
  put 'posts/show_aids/:id' => 'posts#show_aids', as: 'show_aids'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_organizations
  has_many :organizations, :through => :user_organizations
  has_many :posts
  has_many :post_comments
  has_many :aids
  validates :phone, phone: true
  validates :name, presence: true, length: {maximum: 60}

  extend FriendlyId
  friendly_id :name, use: :slugged

  def unread_aids
    @user_posts_aids = Aid.find_by_sql("SELECT * FROM Aids WHERE post_id IN (SELECT id FROM Posts WHERE user_id = " + self.id.to_s + ") AND status = 0")
  end
  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/views/users/show.html.erb
<% content_for :title, @user.name %>
<div class="container">
  <h1>Профиль: <% @user.name  %></h1>
  <p>Номер телефона: <%= @user.phone  %></p>
  <p>Почта: <%= @user.email  %></p>
  <p><%= link_to 'Зарегистрировать организацию',  new_organization_path, class: 'btn btn-primary' %></p>
  <p><%= link_to 'Создать новую тему', new_post_path, class: 'btn btn-primary' %></p>
  <h2>Организации, в которых вы являетесь администратором: </h2>
  <ul>
  <% @owner_organizations.each do |item| %>
    <% if item.organization.active == true %>
      <li><%= item.organization.name %></li>
    <% end %>
  <% end %>
  </ul>
  <h2>Организации, в которых вы являетесь участником: </h2>
  <ul>
    <% @participant_organizations.each do |item| %>
      <% if item.organization.active == true %>
        <li><%= item.organization.name %></li>
      <% end %>
    <% end %>
  </ul>
  <div class="aids-block">
  <h2>Ваши отклики на запросы о помощи:</h2>
  <% @aids.each do |aid| %>
      <div class="aid-item">
        <div class="aid-author">
          <div><b>Опубликовано от имени организации:</b> <%= aid.organization.name %>, <em>дата публикации:</em> <%= aid.created_at %></div>
        </div>
        <p><%= aid.description %></p>
        <% if aid.status == 0 %>
            <div class="aid-status"><b>Статус:</b> Вы откликнулись.</div>
            <div>
              <%= link_to 'Редактировать', edit_aid_path(respond_post: aid.post) %>
              <%= link_to 'Удалить', aid_path, method: :delete, data: { confirm: 'Are you sure?'} %>
            </div>
        <% elsif aid.status == 1 %>
            <div class="aid-status"><b>Статус:</b> Вы оказали помощь, по данному запросу. Благодарим за отклик!!!</div>
        <% else %>
            <div class="aid-status"><b>Статус:</b> Вы откликнулись, но помощь не оказали.</div>
        <% end %>
      </div>
  <% end %>
</div>
</div>