config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'posts/closed_posts' => 'posts#closed_posts', as: 'closed_posts'
  get 'about/index'
  get 'help/index'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  root 'organizations#index'



  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'registrations/show/:id' => 'registrations#show', as: 'user_profile'
  end


  # scope '(/:locale)', locale: /ru/, defaults: { locale: I18n.locale } do
    ActiveAdmin.routes(self)
  # end


  resources :organizations,  only: [ :new, :create, :edit, :update, :destroy]

  post 'organizations/new'

  get 'organizations/show/:id' => 'organizations#show', as: 'organization_show'

  get 'organizations/edit/:id' => 'organizations#edit', as: 'organization_edit'

  get 'organizations/list' => 'organizations#list', as: 'organizations_list'

  get 'organizations/donors' => 'organizations#donors', as: 'donors'

  resources :posts

  resources :post_comments, only: [:create, :edit, :update, :destroy]
  resources :aids

  put 'posts/deactivate/:id' => 'posts#deactivate', as: 'post_deactivate'
  put 'posts/closed/:id' => 'posts#closed', as: 'post_closed'
  put 'organizations/deactivate/:id' => 'organizations#deactivate', as: 'organization_deactivate'
  post 'organizations/participation_request/:id' => 'organizations#participation_request', as: 'organization_participation_request'
  put 'organizations/approved/:id' => 'organizations#approved', as: 'organization_approved'
  put 'aids/accepted/:id' => 'aids#accepted', as: 'aid_accepted'
  get 'organizations/filter_organizations/:id' => 'organizations#filter_organizations', as: 'filter_organizations'
  put 'posts/show_aids/:id' => 'posts#show_aids', as: 'show_aids'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :organization
  belongs_to :user
  belongs_to :post_category
  has_many :post_comments,dependent: :destroy
  has_many :aids , dependent: :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged

  def unshow_aids
    @unshow_posts_aids = Aid.find_by_sql("SELECT * FROM Aids WHERE post_id IN (SELECT id FROM Posts WHERE id = " + self.id.to_s + ") AND status = 0")
  end

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit]
  before_action :correct_user, only: [:edit]
  before_filter :only => [:show, :edit, :update, :destroy,:deactivate, :closed] do
    @post = Post.find_by_slug!(params[:id])
  end

  def index
    @posts = Post.all.where(active: true).order('id DESC').page(params[:page]).per(20)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = t(".create")
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @aids_all = Aid.where(post_id: @post.id)
    @aids = Aid.where(post_id: @post.id, status: 0)
    @aids_real = Aid.where(post_id: @post.id, status: 2)
    @aid = Aid.new
    @respond_post = @post
    @user_already_helped
    unless current_user.nil?
      @user_already_helped = Aid.find_by(user_id: current_user.id, post_id: @post.id)
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def deactivate
    @post.update_attribute(:active, false)
    flash[:success] = t('.deactivate')
    redirect_to posts_path
  end


  def closed
    @post.update_attribute(:open, false)
    redirect_to :back
  end

  def closed_posts
    @post_history = Post.all.where(open: false, active: true, user_id: current_user.id)
  end

  def show_aids
    @post = Post.find(params[:this_post_id])
    @aids = @post.aids.where(status: 0)
    unless @aids.empty?
      @aids.each do |aid|
        aid.update_attribute(:status, 1)
      end
    end
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  private
  def post_params
      params.require(:post).permit(:title, :body, :keywords, :post_category_id, :organization_id, :user_id, :active, :open)
  end

  def correct_user
    @post = Post.find_by_slug!(params[:id])
    redirect_to(@post) unless current_user == @post.user
  end

  def aid_params
    params.require(:aid).permit(:description, :status, :organization_id, :user_id, :post_id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :post_category %>
    <%= f.collection_select :post_category_id, PostCategory.all, :id, :name, class: "form-select from-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.cktext_area :body ,:class => 'ckeditor'%>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <% if current_user.organizations.count == 1 %>
      <p> <%= t(".Published by") %> <%=current_user.organizations.first.name %></p>
      <%= f.hidden_field :organization_id, :value => current_user.organizations.first.id %>
  <% elsif current_user.organizations.count > 1 %>
      <%= f.collection_select :organization_id, current_user.organizations, :id, :name, class: "form-select from-control"  %>
  <% end %>
  <div class="form-group">
    <%= f.submit "#{t(".Publish")}" %>
  </div>
<% end %>

app/views/posts/closed_posts.html.erb
<div class="container closed-post">
  <div class="aids-block">
    <% unless @post_history.empty? %>
      <h2><%= t(".Your closed posts") %></h2>
      <% @post_history.each do |post| %>
        <div class="post-item">
          <div class="inner">
            <h5 class="post-item-link"><%= link_to post.title, post_path(post) %></h5>
            <% unless post.aids.empty? %>
              <span class="show-hide-aids pseudo-link">Cмотреть отклики:</span>
              <ul class="post-aids-list">
                <% post.aids.each do |post_aid| %>
                  <li class="post-item-aid">
                    <div class="aid-author">
                      <div><span class="glyphicon glyphicon-time"></span><%= post_aid.created_at.strftime("%d %b %Y") %></div>
                      <div><span class="glyphicon glyphicon-user"></span><%= post_aid.user.name %></div>
                      <div><span class="glyphicon glyphicon-envelope"></span><%= post_aid.user.email %></div>
                      <div><span class="glyphicon glyphicon-earphone"></span><%= post_aid.user.phone %></div>
                    </div>
                    <div class="aid-org"><%= t(".Organization") %>: <b><%= post_aid.organization.name %></b></div>
                    <div class="aid-description "><%= post_aid.description %></div>
                    <div class="post-item-aid-bot">
                      <% if post_aid.status == 2 %>
                        <span class="glyphicon glyphicon-ok"></span>
                        <em>Автор данного отклика принял реальное участие в оказании помощи по данной публикации!</em>
                      <% end %>
                    </div>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <span class="not-aids-mes">Никто не откликнулся!</span>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>У Вас пока нет закрытых публикаций!</p>
    <% end %>
  </div><!--/aids-block-->
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1><%= t(".Editing post") %></h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% content_for :title, "Все Посты" %>
  <h1><%= t(".All posts") %></h1>
  <%= paginate @posts %>
  <div class="posts-all">
    <% @posts.each do |post| %>
      <% if post.organization.active == true %>
      <div class="post">
        <% (post.open == false) ? panel_class = 'panel post_close' : panel_class = 'panel' %>
        <div class="<%= panel_class %>">
          <% (post.post_category.id == 1) ? div_class = 'panel-category help' : div_class = 'panel-category' %>
          <div class="<%= div_class %>">
            <% if (post.post_category.id == 1) && (post.open == false) %>
              Помощь оказана!
            <% else %>
              <%= post.post_category.name %>!
            <% end %>
          </div>
          <div class="panel-heading">
            <h3 class="panel-title"><%= link_to post.title, post_path(post) %></h3>
          </div>
          <div class="panel-body">
            <div><span class="glyphicon glyphicon-user"></span><%= post.user.name %></div>
            <div><span class="glyphicon glyphicon-time"></span><%= post.created_at.strftime("%d %b %Y" ) %></div>
          </div>
        </div>
      </div><!--/post-->
      <% end %>
  <% end %>
  </div><!--/posts-all-->
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1><%= t(".Add new post") %></h1>
  <%= render 'form' %>
</div>

app/views/posts/nonactiveposts.html.erb
<div class="container">
  <%= t(".Your nonactive posts") %>
  <% @post_history.each do |item|%>
  <ul>
    <li>
      <%= link_to item.title, non_active_path(item) %>
    </li>
  </ul>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="post-detail">
    <div class="row">
      <% if @post.active == true %>
        <div class="post col-md-8">
          <h1><%= @post.title %></h1>
          <% content_for :title, @post.title %>
          <% meta_tag :title, @post.title %>
          <% meta_tag :keywords, @post.keywords %>
          <div class="row">
            <div class="post-info col-md-8">
              <div><span class="glyphicon glyphicon-time"></span><%= @post.created_at.strftime("%d %b %Y") %></div>
              <div><span class="glyphicon glyphicon-filter"></span><%= @post.post_category.name %></div>
              <div><span class="glyphicon glyphicon-user"></span><%= @post.user.name %></div>
              <div><span class="glyphicon glyphicon-map-marker"></span><small>Опубликовано от имени организации:</small><%= @post.organization.name %></div>
            </div>
            <div class="post-action col-md-4">
              <% if user_signed_in? && (current_user == @post.user) %>
                  <%= link_to t(".edit"), edit_post_path(@post) %>
                  <%= link_to t(".delete"), post_deactivate_path(@post), method: :put, data: { confirm: t(".confirm_delete")}%>
              <% end %>
            </div>
          </div>
          <div class="post-body">
            <p><%= @post.body.html_safe %></p>
          </div>
        </div>
        <div class="sidebar col-md-4">
          <% if @post.post_category.id == 1 %>
            <div class="post-status">
              <h3>Статус публикации:</h3>
              <% if user_signed_in? %>
                <% if current_user == @post.user %>
                  <% if @post.open != false %>
                    <p class="opened">Публикация актуальна! Eсли помощь уже оказана, рекомендуем Вам закрыть данную публикацию!</p>
                    <div class="link"><%= link_to "Закрыть", post_closed_path(@post), method: :put %></div>
                  <% else %>
                    <p class="closed"><span class="glyphicon glyphicon-ok"></span>Публикация закрыта! Помощь оказана!</p>
                    <div class="post-report"></div>
                  <% end %>
                <% else %>
                  <% if @post.open != false %>
                    <p class="opened">Публикация актуальна!</p>
                  <% else %>
                    <p class="closed"><span class="glyphicon glyphicon-ok"></span>Публикация закрыта! Помощь оказана!</p>
                  <% end %>
                <% end %>
              <% else %>
                <% if @post.open != false %>
                    <p class="opened">Публикация актуальна!</p>
                    <p>Ecли Вы хотите откликнуться на данный запрос о помощи, Вам необходимо авторизоваться!</p>
                <% else %>
                    <p class="closed"><span class="glyphicon glyphicon-ok"></span>Публикация закрыта! Помощь оказана!</p>
                <% end %>
              <% end %>
            </div><!--/post-status-->
          <% end %>

          <% if user_signed_in? && (@post.post_category.id == 1) && (current_user != @post.user) %>
            <div class="aids-form-block">
              <% if @user_already_helped %>
                <div class="aid-message"><span class="aid-response"><%= t(".You have responded to the request for help!") %></span></div>
              <% else %>
                <div><span class="aid-pseudolink" id="show-hide-aids-form"><%= t(".i want to help") %></span></div>
                <div class="aids-form" id="aids-form">
                  <p><%= t(".We are pleased that you want to help us! Write, please, about your desire to help, and we will contact you by phone or e-mail!") %></p>
                  <div class="form-block">
                    <%= render 'aids/form', btn_txt: t('.Reply') %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>

          <% if @post.post_category.id == 1 %>
            <% unless @aids_all.empty? %>
              <div class="aids-block">
                <% if @post.open != false %>
                  <div class="post-aids-num"><%= t(".Responded") %>: <span><%= @aids_all.length %></span></div>
                  <% @aids_all.each do |aid| %>
                    <div class="aid-item post">
                      <div class="aid-author">
                        <div><span class="glyphicon glyphicon-user"></span><%= aid.user.name %></div>
                        <div><%= t(".Organization") %>: <b><%= aid.organization.name %></b></div>
                      </div>
                      <% if user_signed_in? && (current_user == @post.user) %>
                        <% if aid.status == 0 %>
                          <div class="aid-status">
                            <span class="glyphicon glyphicon-eye-close"></span>
                            <%= link_to t(".View"), user_profile_path(current_user) %>
                          </div>
                        <% else %>
                          <div class="aid-status">
                            <span class="glyphicon glyphicon-eye-open"></span>
                            <span><%= t(".Viewed") %></span>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                <% else %>
                  <% unless @aids_real.empty? %>
                    <h3><%= t(".Assistance was") %>:</h3>
                    <% @aids_real.each do |aid| %>
                      <div class="aid-item post">
                        <div class="aid-author">
                          <div><span class="glyphicon glyphicon-user"></span><%= aid.user.name %></div>
                          <div><%= t(".Organization") %>: <b><%= aid.organization.name %></b></div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
                <p><%= t(".Thank you, everyone who called on this request for help !!!") %></p>
              </div>
            <% else %>
              <p>На данный запрос о помощи нет откликов!</p>
            <% end %>
          <% end %>
        </div><!--/sidebar-->
      </div><!--/row-->

      <div class="comments-list">
        <h2><%= t(".Comments") %>:</h2>
        <div id="hypercomments_widget"></div>
        <script type="text/javascript">
          _hcwp = window._hcwp || [];
          _hcwp.push({widget: "Stream", widget_id: 81181});
          (function () {
            if ("HC_LOAD_INIT" in window)return;
            HC_LOAD_INIT = true;
            var lang = (navigator.language || navigator.systemLanguage || navigator.userLanguage || "en").substr(0, 2).toLowerCase();
            var hcc = document.createElement("script");
            hcc.type = "text/javascript";
            hcc.async = true;
            hcc.src = ("https:" == document.location.protocol ? "https" : "http") + "://w.hypercomments.com/widget/hc/81181/" + lang + "/widget.js";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hcc, s.nextSibling);
          })();
        </script>
        <!--<a href="http://hypercomments.com" class="hc-link" title="comments widget">comments powered by HyperComments</a>-->
      </div>
    <% else %>
        <div class="message-post-deleted">
          <%= t(".Page not found, the post has been deleted!") %>
        </div>
    <% end %>
  </div> <!--/post-detail-->
</div><!--/container-->

app/views/posts/show_aids.js.erb
$('.show_aids').bind('ajax:success', function() {
  $(this).siblings('.mes-ushow-aids').fadeOut();
  $('.red_circle').html('<%= current_user.unread_aids.count %>')
  <% if current_user.unread_aids.count == 0 %>
    $('.red_circle').fadeOut();
  <% end %>
});