config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'posts/closed_posts' => 'posts#closed_posts', as: 'closed_posts'
  get 'about/index'
  get 'help/index'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  root 'organizations#index'



  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'registrations/show/:id' => 'registrations#show', as: 'user_profile'
  end


  # scope '(/:locale)', locale: /ru/, defaults: { locale: I18n.locale } do
    ActiveAdmin.routes(self)
  # end


  resources :organizations,  only: [ :new, :create, :edit, :update, :destroy]

  post 'organizations/new'

  get 'organizations/show/:id' => 'organizations#show', as: 'organization_show'

  get 'organizations/edit/:id' => 'organizations#edit', as: 'organization_edit'

  get 'organizations/list' => 'organizations#list', as: 'organizations_list'

  get 'organizations/donors' => 'organizations#donors', as: 'donors'

  resources :posts

  resources :post_comments, only: [:create, :edit, :update, :destroy]
  resources :aids

  put 'posts/deactivate/:id' => 'posts#deactivate', as: 'post_deactivate'
  put 'posts/closed/:id' => 'posts#closed', as: 'post_closed'
  put 'organizations/deactivate/:id' => 'organizations#deactivate', as: 'organization_deactivate'
  post 'organizations/participation_request/:id' => 'organizations#participation_request', as: 'organization_participation_request'
  put 'organizations/approved/:id' => 'organizations#approved', as: 'organization_approved'
  put 'aids/accepted/:id' => 'aids#accepted', as: 'aid_accepted'
  get 'organizations/filter_organizations/:id' => 'organizations#filter_organizations', as: 'filter_organizations'
  put 'posts/show_aids/:id' => 'posts#show_aids', as: 'show_aids'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord

  after_initialize :set_defaults, unless: :persisted?

  belongs_to :organization_category
  belongs_to :oblast

  has_many :user_organizations
  has_many :posts
  has_many :users, :through => :user_organizations,dependent: :destroy
  has_many :aids
  validates :phone, phone: true
  validates :name, uniqueness: true, presence: true, length: {maximum: 250}
  validates :address, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  validates :oblast_id, presence: true
  validates :location, presence: true 
  validates :organization_category_id, presence: true

  def set_defaults
    self.active = false if self.active.nil?
  end

  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :only => [:show, :edit, :update, :destroy, :participation_request, :deactivate] do
    @organization = Organization.find_by_slug!(params[:id])
  end

  def index
    @posts = Post.all.where(post_category_id:1).order(created_at: :desc).last(4)
    @organization_categories = OrganizationCategory.all.where(active: true)
    @organizations  =  Organization.all.order(created_at: :desc).last(3)
  end

  def new
    if organization_params
      # If data submitted already by the form we call the create method
      create
      p params
      return
    end

    @organization = Organization.new

    render 'new' # call it explicit
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      User.where(admin: true).each do |item|
      UserMailer.welcome_email(item,@organization.slug,@organization.name,current_user).deliver_now
      end
      flash[:success] = t(".create")
      @user_organization = UserOrganization.create!(organization_id: @organization.id,
                                                    user_id: current_user.id, role: 1,approved: true)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def participation_request
    @user_organization = UserOrganization.new(organization_id: @organization.id,
                                              user_id: current_user.id, role: 2,approved: false)
    if @user_organization.save
      flash[:success] = t(".success")
      redirect_to root_path
    end

  end

  def approved
    @user_organization = UserOrganization.find(params[:id])
    @user_organization.update(approved: true)
    flash[:success] = t(".success")
    redirect_to root_path

  end

  def edit

  end

  def update
    if @organization.update(organization_params)
      redirect_to organizations_list_path
    else
      render 'edit'
    end
  end

  def deactivate
    @organization.update_attribute(:active, false)
    flash[:success] = t(".deactivate")
    redirect_to root_path
  end

  def list
    @organization_categories = OrganizationCategory.all.where(active: true).where.not(name: 'Доноры')
    @organizations_all = Organization.all.where(active: true).page(params[:page]).per(3).order('created_at desc')
    @organizations = Organization.where(active: true).select([:id, :name, :latitude, :longitude, :description, :address, :slug])
    @help_requests = Post.where(post_category_id: 1).select([:id, :title, :body, :organization_id,:slug]).group(:organization_id).order('created_at desc')
    respond_to do |format|
      format.html
      format.js {}
      format.json {
        render json: {
            :organizations => @organizations,
            :posts => @help_requests
        }
      }
    end
  end

  def destroy
    @organization.destroy
    redirect_to :back
  end

  def filter_organizations
    @organization_category = OrganizationCategory.find(params[:id])
    @organization_by_category = Organization.where(organization_category_id: @organization_category)
    respond_to do |format|
      format.html
      format.js {}
      format.json {
        render json: {
            :organizations => @organization_by_category
        }
      }
    end
  end

  def donors
    if OrganizationCategory.exists?
      @donor = OrganizationCategory.find_by(name: 'Доноры')
      @organizations = Organization.all.where(active: true).where(organization_category_id: @donor.id)
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end

  def show
    @org_user = @organization.user_organizations.find_by(organization_id: @organization.id,role:1)
    if user_signed_in?
      @org_user_participant = @organization.user_organizations.find_by(organization_id: @organization.id, role:2, user_id: current_user.id)
    end
    @post = Post.where(organization_id: @organization.id)
    unless @org_user.nil?
      @user = @org_user.user
    end
  end

  private
  def organization_params
    if params[:organization].nil?  || params[:organization].empty?
      return false
    else
    return params.require(:organization).permit(:name, :description, :location, :phone, :address, :contact_person,
      :longitude, :latitude, :organization_category_id, :oblast_id, :url, :active, :slug)
    end
  end

  def user_organization_params
    params.require(:user_organization).permit(:role, :organization_id, :user_id, :post,:approved)
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<div class="form-block" id="organization_form">
  <%= form_for @organization, :url => url_action ,class: "form-horizontal" do |f| %>
      <div class="form-group  row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :organization_category_id, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.collection_select :organization_category_id, OrganizationCategory.all, :id, :name, class: "form-select form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :organization_category_id %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :name, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :name, class: "form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :name %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :oblast_id, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.collection_select :oblast_id, Oblast.all, :id, :name, class: "form-select form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :oblast_id %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :longitude, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :longitude, class: "form-control",id:"longitude" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :longitude %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :latitude, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :latitude, class: "form-control",id:"latitude" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :latitude %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :location, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :location, class: "form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :location %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :address, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :address, class: "form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :address %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :contact_person, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :contact_person, class: "form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :contact_person %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :phone, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :phone, placeholder: "0555123456" %>
          <%#= f.text_field :phone, class: "form-control phone", placeholder: "0XXXXXXXXX" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :phone %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :url, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :url, class: "form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :url %>
        </div>
      </div>
      <div class="form-group row <%= 'has-error' if @organization.errors[:name].any? %>">
        <%= f.label :description, class: "col-sm-4 control-label" %>
        <div class="col-sm-6">
          <%= f.cktext_area :description, class: "form-control" %>
          <%= render 'shared/field_errors', object: @organization, field_name: :description %>
        </div>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="form-group move-right col-sm-offset-4">
        <%= f.submit( class: "btn btn-primary") %>
      </div>
  <% end %>
</div>

app/views/organizations/_map_for_form.html.erb
<p><%= t(".Specify the location of the organization on the map") %>:</p>
<button id="map-reset"><%= t(".Reset Map") %></button>
<br><br>
<div id="new-organization-map" class="new-organization-map">
  <button class="pure-button pure-button-primary" id="btn-locate-user"></button>
</div>
<br><br><br>

app/views/organizations/_organizations.html.erb
<div class="organizations">
  <% @organizations_all.each do |organization| %>

    <% if organization.organization_category.name != 'Доноры' %>
    <div>
      <h4><%= link_to organization.name, organization_show_path(organization)%>,
          <em>(категория: <%= organization.organization_category.name %>)</em></h4>
      <ul>
        <li><%= t(".Location") %>: <%= organization.location %></li>
        <li><%= t(".Region") %>: <%= organization.oblast.name %></li>
        <li><%= t(".Adress") %>: <%= organization.address %></li>
        <li><%= t(".Phone") %>: <%= organization.phone %></li>
      </ul>
    </div>

    <% end %>
  <% end %>
</div>

app/views/organizations/donors.html.erb
<div class="container">
  <h1><%= t(".Organizations Aids") %>:</h1>
  <% unless @organizations.empty? %>
    <% @organizations.each do |organization| %>
      <h4><%= link_to organization.name, organization_show_path(organization) %></h4>
      <ul>
        <li><%= t(".Location") %>: <%= organization.location %></li>
        <li><%= t(".Region") %>: <%= organization.oblast.name %></li>
        <li><%= t(".Adress") %>: <%= organization.address %></li>
        <li><%= t(".Phone") %>: <%= organization.phone %></li>
      </ul>
    <% end %>
  <% else %>
    <p>Нет зарегистрированных организаций - доноров!</p>
  <% end %>
</div>

app/views/organizations/edit.html.erb
<div class="container">
  <h1 class="al-center"><%= t(".Edit organization") %></h1>
  <div class="row">
      <div class="col-md-6 form-block">
        <%=  render 'form', url_action:  {:action => :update} %>
      </div>
      <div class="col-md-6">
        <%= render 'map_for_form' %>
      </div>
  </div>
</div>

app/views/organizations/index.html.erb
<div class="container">
  <div class="row">
   <div class="legend_box">
      <div class="imagebox col-md-3">
        <div class="wrap">
          <%= image_tag '/assets/map/icon-marker-alert.svg' %>
        </div>
        <div> <%= t(".Organizations that needs help") %></div>
      </div>
      <div class="imagebox col-md-3">
        <div class="wrap">
          <%= image_tag '/assets/map/icon-marker-ok.svg' %>
        </div>
        <div><%= t(".Social organizations") %></div>
      </div>
      <div class="imagebox col-md-3">
        <div class="wrap">
          <%= image_tag '/assets/map/icon-marker-user.svg' %>
        </div>
        <div><%= t(".Your location") %></div>
      </div>
      <div class="imagebox col-md-3">
        <div class="wrap">
          <%= image_tag '/assets/my_icon.png' %>
        </div>
        <div><%= t(".My location") %></div>
      </div>
     <div class="imagebox col-md-3">
       <div><a href="#post_section" class="link-scroll btn btn-primary"><%= t(".Last posts")%></a></div>
     </div>
    </div>
  </div>
</div>

<div id="main-map" class="main-map">
  <button class="pure-button" id="btn-locate-user"></button>

</div>
<br><br>
<ul id="result"></ul>
<div class="container" id="post_section">
  <% content_for :title, "Главная" %>
  <h2><%= t(".Request about help") %></h2>
    <div class="posts-all">
      <% @posts.each do |post| %>
          <div class="post">
            <div class="panel">
              <div class="panel-heading">
                <h3 class="panel-title"><%= link_to post.title, post_path(post) %></h3>
              </div>
              <div class="panel-body">
                <div><span class="glyphicon glyphicon-user"></span><%= post.user.name %></div>
                <div><span class="glyphicon glyphicon-time"></span><%= post.created_at.strftime("%d %b %Y" ) %></div>
              </div>
            </div>
          </div>
      <% end %>

    </div>

    <div class="new_organization col-md-12">
      <h2><%= t(".New organizations") %></h2>
      <hr>
         <% @organizations.each do |organization| %>
            <div class="col-md-4">
                  <h4><%= link_to organization.name, organization_show_path(organization) %></h4>
                  <ul>
                    <li><%= t(".Location") %>: <%= organization.location %></li>
                    <li><%= t(".Region") %>: <%= organization.oblast.name %></li>
                    <li><%= t(".Adress") %>: <%= organization.address %></li>
                    <li><%= t(".Phone") %>: <%= organization.phone %></li>
                  </ul>
            </div>
        <% end %>

    </div>
  <br>
  <br>

</div>

app/views/organizations/list.html.erb
<% content_for :title, "Все организации" %>
<div class="container">
  <h1><%= t(".List of all organizations") %></h1>
  <div class="category_filter">
    <p><%= t(".Select a category") %>:</p>
    <div class="form-group">
      <%= select_tag "organization_category_id", options_from_collection_for_select(@organization_categories, "id", "name"), :prompt => t(".All organizations"), id: "filter_org" %>
    </div>
  </div>

  <div id="organization-list">
    <%= paginate @organizations_all %>
    <%= render :partial => 'organizations', :object => @organizations_all %>
  </div>

</div>

app/views/organizations/new.html.erb
<div class="container">
  <h1 class="al-center"><%= t(".Register your organization") %></h1>
  <div class="row">
    <div class="col-md-6 form-block">
      <%=  render 'form', url_action:  {:action => :new} %>
    </div>
    <div class="col-md-6">
      <%= render 'map_for_form' %>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<% content_for :title, @organization.name %>

<% meta_tag :title, "#{@organization.name}, #{@organization.location}, #{@organization.oblast.name}" %>
<% meta_tag :keywords, @organization.keywords  %>
<% meta_tag :description, @organization.description  %>

<div class="container">
  <h1><%= @organization.name %></h1>
  <div class="row">
    <div class="col-md-6">
      <h5><%= t(".General information about the organization") %>:</h5>
      <ul>
        <li><%= t(".Description") %>: <%= @organization.description.html_safe %></li>
        <li><%= t(".Location") %>: <%= @organization.location %></li>
        <li><%= t(".Oblast") %>: <%= @organization.oblast.name %></li>
        <li><%= t(".Address") %>: <%= @organization.address %></li>
        <li><%= t(".Phone") %>: <%= @organization.phone %></li>
      </ul>
    </div>
    <div class="col-md-6">
      <h4><%= t(".Location of organization on the map") %>:</h4>
      <% unless @organization.latitude.empty? || @organization.longitude.empty? %>
        <div class="org-coordinate">
          <div id="org-latitude"><%= @organization.latitude %></div>
          <div id="org-longitude"><%= @organization.longitude %></div>
        </div>
        <div id="organization-map" class="organization-map"></div>
      <% else %>
      <p><%= t(".For the organization is no information on its location on the map!") %></p>
      <% end %>
    </div>
  </div><!--/row-->
  <div>
    <% if user_signed_in? %>
      <% if current_user == @user %>
        <%= link_to t('.Edit'), edit_organization_path(@organization) %>
      <% elsif @org_user_participant == nil %>
        <%= link_to t('.join to organization'), organization_participation_request_path(@organization), method: :post %>
      <% end  %>
    <% end %>
  </div>
  <% unless @post.empty? %>
  <div class="post-all-orgs">
    <h3><%= t('.Publications') %>:</h3>
    <div class="posts-all">
      <% @post.each do |post| %>
          <div class="post">
            <div class="panel">
              <% (post.post_category.id == 1) ? div_class = 'panel-category help' : div_class = 'panel-category' %>
              <div class="<%= div_class %>">
                <%= post.post_category.name %>!
              </div>
              <div class="panel-heading">
                <h3 class="panel-title"><%= link_to post.title, post_path(post) %></h3>
              </div>
              <div class="panel-body">
                <div><span class="glyphicon glyphicon-user"></span><%= post.user.name %></div>
                <div><span class="glyphicon glyphicon-time"></span><%= post.created_at.strftime("%d %b %Y" ) %></div>
              </div>
            </div>
          </div><!--/post-->
      <% end %>
    </div>
  </div><!--/post-all-orgs-->
  <% end %>
</div>