config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'posts/closed_posts' => 'posts#closed_posts', as: 'closed_posts'
  get 'about/index'
  get 'help/index'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  root 'organizations#index'



  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'registrations/show/:id' => 'registrations#show', as: 'user_profile'
  end


  # scope '(/:locale)', locale: /ru/, defaults: { locale: I18n.locale } do
    ActiveAdmin.routes(self)
  # end


  resources :organizations,  only: [ :new, :create, :edit, :update, :destroy]

  post 'organizations/new'

  get 'organizations/show/:id' => 'organizations#show', as: 'organization_show'

  get 'organizations/edit/:id' => 'organizations#edit', as: 'organization_edit'

  get 'organizations/list' => 'organizations#list', as: 'organizations_list'

  get 'organizations/donors' => 'organizations#donors', as: 'donors'

  resources :posts

  resources :post_comments, only: [:create, :edit, :update, :destroy]
  resources :aids

  put 'posts/deactivate/:id' => 'posts#deactivate', as: 'post_deactivate'
  put 'posts/closed/:id' => 'posts#closed', as: 'post_closed'
  put 'organizations/deactivate/:id' => 'organizations#deactivate', as: 'organization_deactivate'
  post 'organizations/participation_request/:id' => 'organizations#participation_request', as: 'organization_participation_request'
  put 'organizations/approved/:id' => 'organizations#approved', as: 'organization_approved'
  put 'aids/accepted/:id' => 'aids#accepted', as: 'aid_accepted'
  get 'organizations/filter_organizations/:id' => 'organizations#filter_organizations', as: 'filter_organizations'
  put 'posts/show_aids/:id' => 'posts#show_aids', as: 'show_aids'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<%= csrf_meta_tags %>
<header id="header_top">
  <nav class="navbar navbar-fixed-top">
    <div class="container">
      <%= link_to image_tag("logo2.png"), root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <li><%= link_to t("layouts._header.Donors"), donors_path %></li>
        <li><%= link_to t("layouts._header.Organizations"), organizations_list_path %></li>
        <li><%= link_to t("layouts._header.All Posts"), posts_path %></li>
        <li><%= link_to t("layouts._header.About Project"), about_index_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('layouts._header.select language') %><span class="caret"></span></a>
          <ul class="dropdown-menu lang">
            <%= link_to "English", change_locale_path(:en) %>
            <li role="separator" class="divider"></li>
            <%= link_to "Kyrgyz", change_locale_path(:kg) %>
            <li role="separator" class="divider"></li>
            <%= link_to "Russian", change_locale_path(:ru) %>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <ul class="nav navbar-nav">

              <li class="new_message">

                <%= link_to(user_profile_path(current_user), class: " glyphicon glyphicon-envelope") do %>
                  <% if current_user.unread_aids.count > 0 %>
                  <span class="red_circle">
                    <%= current_user.unread_aids.count %>
                  </span>
                    <% end %>
                <% end %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('layouts._header.View profile') %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li> <%if current_user.admin? %>
                        <%= link_to t("layouts._header.Dashboard"),admin_dashboard_path %>
                    <%end %></li>
                  <li><%= link_to t('layouts._header.View profile'), user_profile_path(current_user)  %></li>
                  <li><%= link_to t('layouts._header.Edit profile'), edit_user_registration_path(current_user) %></li>
                  <li><%= link_to t('layouts._header.Register the organization'), new_organization_path %></li>
                  <li><%= link_to t('layouts._header.Create new post'), new_post_path %></li>
                  <li><%= link_to t('layouts._header.Help'), help_index_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to t('layouts._header.Exit'), destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else  %>
          <%= link_to t('layouts._header.Registration'), new_user_registration_path, class: 'btn btn-primary navbar-btn'  %>
          <%= link_to t('layouts._header.Sign in'), new_user_session_path, class: 'btn btn-primary navbar-btn'  %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>
    <%= if content_for?(:title) then yield(:title) + ' | ' end %>
    Social hubs
  </title>
  <% if MetaTag.exists? %>
  <meta name='title' content='<%= yield_meta_tag(:title, MetaTag.last.title) %>' />
  <meta name='description'
        content='<%= yield_meta_tag(:description, MetaTag.last.description) %>' />
  <meta name='keywords'
        content='<%= yield_meta_tag(:keywords, MetaTag.last.keywords ) %>' />
  <% end %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,700&amp;subset=cyrillic-ext" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="all">
    <%= render 'layouts/header' %>
    <% flash.each do |type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{type}" %>
    <% end %>
    <%= yield %>
    <div class="pseudo-footer"></div>
  </div>
  <footer>
    <div class="container">
      <div class="col-md-12">
        <p>Copyright © 2016&nbsp; <a href="http://it-attractor.com">IT-Attractor Plus</a></p>
      </div>
      <a href="#header_top" class="headertop link-scroll"></a>
    </div>
  </footer>
</body>
</html>